name: Doxygen

on:
  push:
    branches: [ master ]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mattnotmitt/doxygen-action@v1
        with:
            working-directory: '.'
            doxyfile-path: 'docs/Doxygen'
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Doxygen Robot
        author_email: robot@example.com
        message: 'Committing Doxygen docs'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
