name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [ master ]

jobs:
  job:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Makefile
        run: cmake .
      - name: Build
        run: make
      - name: Test
        run: make test
